// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ListPeopleStreamReq struct {
	NameFilter string `json:"nameFilter"`
	StatType   int    `json:"StatType"`
}

type PaginationInput struct {
	Skip int `json:"skip"`
	Take int `json:"take"`
}

type PeopleStream struct {
	BuildingName string `json:"buildingName"`
	FloorNum     string `json:"FloorNum"`
	SpaceName    string `json:"SpaceName"`
	SpaceID      string `json:"SpaceId"`
	DeviceName   string `json:"DeviceName"`
	IotCode      string `json:"IotCode"`
	MonitorType  string `json:"MonitorType"`
	Unit         string `json:"Unit"`
	Num          int    `json:"Num"`
	Status       string `json:"Status"`
}
